# Generated by Django 4.1.3 on 2022-11-22 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamingworld', '0003_fabricante_genero_seccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fabricante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gamingworld.fabricante'),
        ),
        migrations.AddField(
            model_name='producto',
            name='genero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gamingworld.genero'),
        ),
        migrations.AddField(
            model_name='producto',
            name='seccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gamingworld.seccion'),
        ),
    ]
