# Generated by Django 4.1.3 on 2022-11-29 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamingworld', '0004_producto_fabricante_producto_genero_producto_seccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=400)),
                ('telefono', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=300)),
                ('correo', models.EmailField(max_length=254)),
                ('tarjeta', models.CharField(max_length=30)),
                ('order_id', models.PositiveBigIntegerField(default=0)),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gamingworld.producto')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gamingworld.estadopedido')),
            ],
        ),
    ]
