# Generated by Django 4.1.3 on 2022-11-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamingworld', '0005_estadopedido_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='order_id',
            field=models.PositiveBigIntegerField(default=0, unique=True),
        ),
    ]
