# Generated by Django 4.1.3 on 2022-12-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamingworld', '0005_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
