# Generated by Django 4.1.3 on 2022-12-10 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamingworld', '0006_compra_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='productos',
        ),
        migrations.AddField(
            model_name='compra',
            name='productos',
            field=models.ManyToManyField(to='gamingworld.producto'),
        ),
    ]
