# Generated by Django 4.1.3 on 2022-12-10 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamingworld', '0007_remove_compra_productos_compra_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='productos',
        ),
    ]
