# Generated by Django 4.1.3 on 2022-12-10 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamingworld', '0008_remove_compra_productos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprasProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamingworld.compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamingworld.producto')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='productos',
            field=models.ManyToManyField(through='gamingworld.ComprasProductos', to='gamingworld.producto'),
        ),
    ]
