# Generated by Django 4.1.3 on 2022-12-11 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamingworld', '0010_compra_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='order_id',
            field=models.PositiveBigIntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gamingworld.estadopedido'),
        ),
    ]
