# Generated by Django 4.1.3 on 2022-12-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamingworld', '0011_estadopedido_compra_order_id_compra_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='order_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
